import { beforeEach, expect, it, vi } from "vitest";
import { env } from "cloudflare:test";
import type { Env } from "../../src/env";
import { applySchema } from "../db/apply-schema";
import { createPendingSubscription, activateByToken } from "../../src/db/subscriptions";
import { addArtistToSubscription } from "../../src/db/subscription-artists";
import { upsertShow } from "../../src/db/shows";
import { persistMatches } from "../../src/db/show-artists";
import { runNotifications } from "../../src/pipeline/notify";
import { SubrequestBudget } from "@/lib/budget";

beforeEach(applySchema);

// The ambient `Cloudflare.Env` type (worker-configuration.d.ts, generated by
// `wrangler types`) only reflects bindings declared in wrangler.jsonc/.dev.vars
// and is missing the app-level vars (APP_BASE_URL, INTERNAL_SECRET, etc.) that
// `vitest.config.mts`'s `miniflare.bindings` actually supplies at runtime for
// this test env. Cast to our own `Env` (src/env.ts), which is the real shape.
const typedEnv = env as unknown as Env;

it("sends one reminder per candidate and marks shows sent", async () => {
  const sub = await createPendingSubscription(env.DB, "a@b.com", ["110000"]);
  await activateByToken(env.DB, sub.token);
  const artistId = await addArtistToSubscription(env.DB, sub.id, "刺猬");
  const show = await upsertShow(env.DB, {
    showstartId: "1", title: "刺猬专场", cityCode: "110000", venue: "MAO",
    showTime: "2026-08-01T20:00:00", price: "180", url: "https://x/1", performers: ["刺猬"],
    poster: "https://s2.showstart.com/1.jpg",
  });
  await persistMatches(env.DB, [{ showId: show.id, artistId, matchedBy: "performer" }]);

  const sendMock = vi.fn(async () => new Response(JSON.stringify({ id: "1" }), { status: 200 }));
  vi.stubGlobal("fetch", sendMock); // no RESEND_API_KEY in test env -> console provider, fetch unused
  const res = await runNotifications(env.DB, typedEnv);
  expect(res.sent).toBe(1);
  // second run: already notified, nothing to send
  expect((await runNotifications(env.DB, typedEnv)).sent).toBe(0);
  vi.unstubAllGlobals();
});

it("stops sending when the subrequest budget runs out; unsent reminders go out on the next run", async () => {
  const artistShow = await upsertShow(env.DB, {
    showstartId: "b1", title: "刺猬专场", cityCode: "110000", venue: "MAO",
    showTime: "2026-08-01T20:00:00", price: "180", url: "https://x/b1", performers: ["刺猬"],
    poster: null,
  });
  for (const email of ["one@b.com", "two@b.com", "three@b.com"]) {
    const sub = await createPendingSubscription(env.DB, email, ["110000"]);
    await activateByToken(env.DB, sub.token);
    const artistId = await addArtistToSubscription(env.DB, sub.id, "刺猬");
    await persistMatches(env.DB, [{ showId: artistShow.id, artistId, matchedBy: "performer" }]);
  }

  // budget 2 = two send attempts; the third candidate is deferred, not failed
  const first = await runNotifications(env.DB, typedEnv, new SubrequestBudget(2));
  expect(first.sent).toBe(2);
  expect(first.failed).toBe(0);

  // next run (fresh budget) picks up the deferred one — nothing lost
  const second = await runNotifications(env.DB, typedEnv, new SubrequestBudget(2));
  expect(second.sent).toBe(1);
});

// A reminder for a gig that already happened is worse than no reminder. The
// listing is normally upcoming-only, but the search API will happily serve shows
// from years back (sortType 4/5 return 2023 dates), so the guard belongs here
// rather than resting on an assumption about the crawler's input.
it("never reminds about a show that has already happened", async () => {
  const sub = await createPendingSubscription(env.DB, "past@b.com", ["110000"]);
  await activateByToken(env.DB, sub.token);
  const artistId = await addArtistToSubscription(env.DB, sub.id, "刺猬");
  const gone = await upsertShow(env.DB, {
    showstartId: "past", title: "去年的演出", cityCode: "110000", venue: "MAO",
    showTime: "2023-08-01T20:00:00", price: "180", url: "https://x/past", performers: ["刺猬"],
    poster: null,
  });
  await persistMatches(env.DB, [{ showId: gone.id, artistId, matchedBy: "performer" }]);

  expect((await runNotifications(env.DB, typedEnv)).sent).toBe(0);
});

// A festival's showTime can be an unparseable date range ("2026.09.04－09.06"),
// which normalizeShowTime turns into null. Those are still upcoming as far as we
// know, so they must not be silently dropped by the date filter.
it("still reminds about a show whose date could not be parsed", async () => {
  const sub = await createPendingSubscription(env.DB, "tbd@b.com", ["110000"]);
  await activateByToken(env.DB, sub.token);
  const artistId = await addArtistToSubscription(env.DB, sub.id, "刺猬");
  const undated = await upsertShow(env.DB, {
    showstartId: "tbd", title: "音乐节", cityCode: "110000", venue: null,
    showTime: null, price: null, url: "https://x/tbd", performers: ["刺猬"], poster: null,
  });
  await persistMatches(env.DB, [{ showId: undated.id, artistId, matchedBy: "performer" }]);

  expect((await runNotifications(env.DB, typedEnv)).sent).toBe(1);
});
